[env]
TERM = "xterm-256color"

[window]
position = {x = 500, y = 250}
dynamic_padding = true
padding = {x = 0,y = 1}
opacity = 0.95
blur = true

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}
size = 9

[cursor]
style = {shape = "Block", blinking = "On"}

[mouse]
hide_when_typing = false

[colors.primary]
background = "#1f2335"
foreground = "#c0caf5"
dim_foreground = "#565f89"
bright_foreground = "#c0caf5"

[colors.cursor]
text = "#1f2335"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1f2335"
cursor = "#bb9af7"

[colors.search.matches]
foreground = "#1f2335"
background = "#7dcfff"

[colors.search.focused_match]
foreground = "#1f2335"
background = "#9ece6a"

[colors.footer_bar]
foreground = "#1f2335"
background = "#565f89"

[colors.hints.start]
foreground = "#1f2335"
background = "#e0af68"

[colors.hints.end]
foreground = "#1f2335"
background = "#565f89"

[colors.selection]
text = "#1f2335"
background = "#ff9e64"

[colors.normal]
black = "#565f89"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#2ce8e8"
white = "#c0caf5"

[colors.bright]
black = "#565f89"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#2ce8e8"
white = "#c0caf5"

