# --- Font Configuration ---
font_family      Liga SFMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

# --- Transparency Settings ---
background_opacity         0.85   

# --- Color Scheme (Custom Dark Earth/Olive) ---
background       #222017
foreground       #969992
selection_background #48351b
selection_foreground #d08f2a
cursor           #d08f2a

# Normal colors
color0  #222017
color1  #372817
color2  #969992
color3  #48351b
color4  #d08f2a
color5  #372817
color6  #969992
color7  #969992

# Bright colors
color8  #48351b
color9  #372817
color10 #969992
color11 #48351b
color12 #d08f2a
color13 #372817
color14 #969992
color15 #ffffff

# --- Alacritty/Kitty "Vi-Mode" Muscle Memory Bind ---
map ctrl+shift+space show_scrollback
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
