# --- Font Configuration ---
font_family      Liga SFMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13

# --- Transparency Settings ---
background_opacity         0.9

# --- Alacritty/Kitty "Vi-Mode" ---
map ctrl+shift+space show_scrollback
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

# Get colors from wallust
include ~/.cache/wallust/kitty-colors.conf

allow_remote_control yes
