return {}
-- Tried neo tree (written by chatGPT, did not like it)
-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   branch = "v3.x",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-tree/nvim-web-devicons", -- optional but recommended
--     "MunifTanjim/nui.nvim",
--   },
--   lazy = false, -- load on startup
--   config = function()
--     require("neo-tree").setup({
--       close_if_last_window = false,
--       enable_git_status = true,
--       enable_diagnostics = false,
--       default_component_configs = {
--         indent = {
--           with_markers = true,
--         },
--         icon = {
--           folder_closed = "", -- same as your nvim-tree config
--           folder_open = "",
--         },
--         git_status = {
--           symbols = {
--             -- customize if needed
--           },
--         },
--       },
--       window = {
--         width = 30,
--         mappings = {
--           ["<space>"] = "toggle_node",
--           ["<cr>"] = "open",
--           ["S"] = "open_split",
--           ["s"] = "open_vsplit",
--           ["C"] = "close_node",
--           ["z"] = "close_all_nodes",
--           ["a"] = "add",
--           ["d"] = "delete",
--           ["r"] = "rename",
--           ["y"] = "copy_to_clipboard",
--           ["x"] = "cut_to_clipboard",
--           ["p"] = "paste_from_clipboard",
--           ["c"] = "copy",
--           ["m"] = "move",
--           ["q"] = "close_window",
--         },
--       },
--       filesystem = {
--         follow_current_file = {
--           enabled = true,
--         },
--         filtered_items = {
--           visible = true,
--           hide_dotfiles = false,
--           hide_gitignored = false,
--           never_show = { ".DS_Store" },
--         },
--       },
--     })
--
--     -- Keymaps like your old nvim-tree ones
--     local keymap = vim.keymap
--     keymap.set("n", "<leader>ee", "<cmd>Neotree toggle<CR>", { desc = "Toggle file explorer" })
--     keymap.set("n", "<leader>ef", "<cmd>Neotree reveal<CR>", { desc = "Reveal current file in explorer" })
--     keymap.set("n", "<leader>ec", "<cmd>Neotree close<CR>", { desc = "Close file explorer" })
--   end,
-- }
